"use client";
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ConvexProvider, ConvexReactClient } from "convex/react";
import { KindeProvider } from "@kinde-oss/kinde-auth-nextjs";
import { Toaster } from "../components/ui/toaster"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const convex = new ConvexReactClient(process.env.NEXT_PUBLIC_CONVEX_URL!);

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Police app",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <Navbar/>
        <Toaster />

        <KindeProvider>
          <ConvexProvider client={convex}>
            {children}
          </ConvexProvider>
        </KindeProvider>
      </body>
    </html>
  );
}